# Generated by Django 4.2.5 on 2023-10-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("furnitures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="furniture",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="furnitures",
                to="furnitures.furniturecategory",
            ),
        ),
    ]
