# Generated by Django 4.2.5 on 2023-10-05 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=145)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Motor",
            fields=[
                (
                    "baseclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.baseclass",
                    ),
                ),
                ("brand", models.CharField(max_length=145)),
                ("model", models.CharField(max_length=145)),
                ("fuel", models.CharField(max_length=50)),
                ("transmission", models.CharField(max_length=145)),
                ("year", models.PositiveBigIntegerField()),
                ("color", models.CharField(max_length=50)),
                ("images", models.FileField(upload_to="")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="motor_app.motorcategory",
                    ),
                ),
            ],
            bases=("core.baseclass",),
        ),
    ]
