# Generated by Django 4.2.5 on 2023-10-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=145)),
            ],
        ),
        migrations.CreateModel(
            name="Motor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=145)),
                ("model", models.CharField(max_length=145)),
                ("fuel", models.CharField(max_length=50)),
                ("transmission", models.CharField(max_length=145)),
                ("year", models.PositiveBigIntegerField()),
                ("color", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=255)),
                ("price", models.PositiveBigIntegerField()),
                ("images", models.ImageField(upload_to="")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="motor_app.category",
                    ),
                ),
            ],
        ),
    ]
