# Generated by Django 4.2.5 on 2023-10-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motor_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motor",
            name="price",
            field=models.CharField(max_length=255),
        ),
    ]
