# Generated by Django 4.2.5 on 2023-10-12 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("motor_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motor",
            name="images",
        ),
    ]
