# Generated by Django 4.2.5 on 2023-10-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motor_app", "0002_alter_motor_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motor",
            name="images",
            field=models.FileField(upload_to=""),
        ),
    ]
