# Generated by Django 4.2.5 on 2023-10-03 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("motor_app", "0003_alter_motor_images"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="MotorCategory",
        ),
    ]
