# Generated by Django 4.2.5 on 2023-10-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=245)),
                ("description", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("phone_number1", models.CharField(max_length=100)),
                ("phone_number2", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
