# Generated by Django 4.2.5 on 2023-10-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseclass",
            name="description",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="baseclass",
            name="location",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="baseclass",
            name="name",
            field=models.CharField(default=0, max_length=245),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="baseclass",
            name="price",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
