# Generated by Django 4.2.5 on 2023-10-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_baseclass_description_baseclass_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baseclass",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="baseclass",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="baseclass",
            name="phone_number1",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="baseclass",
            name="phone_number2",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
