# Generated by Django 4.2.5 on 2023-10-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_profile_profile_img"),
        ("core", "0002_baseclass_created_at_baseclass_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseclass",
            name="liked_by",
            field=models.ManyToManyField(related_name="offers", to="users.profile"),
        ),
    ]
