# Generated by Django 4.2.5 on 2023-10-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_name_baseclass_title_baseclass_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseclass",
            name="phone_number1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="baseclass",
            name="phone_number2",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
