# Generated by Django 4.2.5 on 2023-10-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_imagebase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseclass",
            name="phone_number2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="imagebase",
            name="image",
            field=models.ImageField(upload_to="publication_images/"),
        ),
    ]
