# Generated by Django 4.2.5 on 2023-10-11 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_baseclass_liked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseclass",
            name="liked_by",
        ),
    ]
