# Generated by Django 4.2.5 on 2023-10-12 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_baseclass_phone_number2_alter_imagebase_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagebase",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.baseclass",
            ),
        ),
    ]
