# Generated by Django 4.2.5 on 2023-10-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_baseclass_user"),
        ("users", "0002_alter_profile_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="favorites", to="core.baseclass"
            ),
        ),
    ]
