# Generated by Django 4.2.5 on 2023-10-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='images/user_default_icon.png', null=True, upload_to='images/profile_imgs'),
        ),
    ]
