# Generated by Django 4.2.5 on 2023-10-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entertainments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entertainment",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Entertainments",
                to="entertainments.entertainmentcategory",
            ),
        ),
    ]
